services:
  - type: web
    name: mlp-digit-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT src.backend.app:app"
    workingDir: src/backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
